// Curated motivational quote library for InnerHP
export const DAILY_QUOTES = [
  "Every small step forward strengthens your journey.",
  "You don't have to be a whole forest today. Be a single, soft leaf.",
  "Rest is part of the adventure, not a pause from it.",
  "Your spirit is allowed to be quiet and still mighty.",
  "Gentle effort still moves the world.",
  "Today, kindness towards yourself is the bravest quest.",
  "Healing is not linear, but it is always forward.",
  "Breathe. The next moment is yours.",
  "You have survived 100% of your hardest days.",
  "Soft hearts carry the heaviest courage.",
  "Tend to your inner garden — it blooms in seasons.",
  "Even slow flames warm the night.",
  "Pause. Sip water. You are doing better than you think.",
  "Your worth is not measured in productivity.",
  "You are allowed to rewrite your own story today.",
  "Tiny rituals, mighty results.",
  "The morning sun rises for you too.",
  "Be the friend you wish you had.",
  "A calm mind is a sharp sword.",
  "Plant a thought of hope and water it gently.",
  "Your feelings are messengers, not enemies.",
  "Listen to the whisper before it becomes a scream.",
  "Stillness is a kind of magic.",
  "Even heroes nap.",
  "Soft is not weak — soft is wise.",
  "The map of your day is yours to draw.",
  "Notice one beautiful thing right now.",
  "Today, choose ease over perfection.",
  "Inner courage doesn't roar — it whispers 'try again'.",
  "Let go of what you cannot carry today.",
  "Some days the quest is simply showing up.",
  "You are not behind. You are exactly here.",
  "Make peace with the pace of your becoming.",
  "Brew a hot drink. Restore +5 HP.",
  "Your story has many chapters; this is just one page.",
  "Strength looks like softness more often than you think.",
  "Trust the slow, golden alchemy of small habits.",
  "Today you may rest your sword.",
  "Inner peace is a choice you make on repeat.",
  "Bright stars are born in dark skies.",
  "Drink water, hero. The world can wait a minute.",
  "Even the moon glows in pieces.",
  "Be patient with the unfinished parts of you.",
  "You are worthy of the love you give to others.",
  "Your mind is a sanctuary; treat it like one.",
  "Sleep well — tomorrow's quests await.",
  "Walk gently through your own thoughts.",
  "You don't have to earn rest.",
  "Beauty exists inside ordinary moments.",
  "Soft mornings make brave afternoons.",
  "Let today be enough.",
  "Notice your breath. Notice it again.",
  "You are growing in ways you cannot see yet.",
  "Compassion towards yourself is a radical act.",
  "Your light does not need to be loud to matter.",
  "Pause is not failure. Pause is wisdom.",
  "Brave the world with a kind heart.",
  "Wherever you are, that's where the journey continues.",
  "Today's smallest joy is still joy.",
  "Move slowly. You'll still arrive.",
  "Choose what nourishes, not what numbs.",
  "There is room in this life for you to rest.",
  "Quiet days build loud strength.",
  "Be a soft place for your own thoughts to land.",
  "Your effort matters, even when invisible.",
  "Inhale calm. Exhale weight.",
  "Hope is a habit. Practice it.",
  "Your worth is not a moving target.",
  "Let curiosity replace judgement today.",
  "A small act of self-care is still self-care.",
  "You are doing the brave, ordinary work.",
  "The path lights up one step at a time.",
  "Carry less today. The world will still turn.",
  "Your soul speaks softly. Listen.",
  "Even cloudy days are part of the sky.",
  "You are not your hardest day.",
  "The companion in the mirror is rooting for you.",
  "Wonder is medicine.",
  "Soft breath, soft heart, soft start.",
  "Choose one tiny kindness for yourself today.",
  "Make space for what makes you feel alive.",
  "Your tenderness is a superpower.",
  "Stillness, too, is a form of motion.",
  "Take the long way home — there's poetry on it.",
  "Today, let 'enough' be the goal.",
  "Even small light pushes back the dark.",
  "Be where your feet are.",
  "Lay your worries down. Pick them up gentler.",
  "You don't have to bloom every day.",
  "Soft hands can still build mountains.",
  "There is courage in trying again.",
  "Wrap yourself in patience today.",
  "You are the hero, the healer, and the home.",
  "Quiet wins still count.",
  "Let go of the day's weight before sleep.",
  "Your story is far from over.",
  "Even now, you are becoming.",
  "Rest is sacred. Honor it.",
  "Be soft with the parts of you still healing.",
  "Walk forward without rushing.",
  "Today is a soft, unfinished page.",
  "Spell of the day: 'I am allowed to be okay'.",
];

export const QUEST_COMPLETE_QUOTES = [
  "Quest completed. Your spirit grows stronger.",
  "A small victory, a steady step.",
  "Well done, adventurer. Your HP rises.",
  "The world feels lighter. So do you.",
  "Another stone laid on the path of becoming.",
  "Your inner companion smiles.",
  "The journal records another brave moment.",
  "+HP. +Hope.",
  "The fog clears just a little.",
  "Today, you out-walked the doubt.",
  "Magic restored — bit by bit.",
  "Your spirit gem glows brighter.",
  "Steady, steady. Beautifully done.",
  "The realm is kinder because of you.",
  "You showed up. That's the whole spell.",
  "Tiny ritual, lasting magic.",
  "Your light just leveled up.",
  "Quest closed. Heart open.",
  "The wind sings your name.",
  "Soft strength is still strength.",
  "Look at you, taking care of you.",
  "Adventure log: today, kindness won.",
  "Your future self thanks you.",
  "A breath, a step, a triumph.",
  "Your inner ember burns warmer.",
  "The map of self-care lights up.",
  "Another quest, another small healing.",
  "Brave, kind, and unstoppable in your own pace.",
  "Saved at the campfire. +HP restored.",
  "Even the stars noticed.",
  "Hero, you've earned a smile.",
  "Your courage gauge is glowing.",
  "The mountain looks smaller now.",
  "You're writing a softer story.",
  "Inner compass: pointing true.",
  "A new page in the adventure journal.",
  "Calm collected. Wisdom unlocked.",
  "Your soul just did a happy little dance.",
  "Quest log: 'Today, I chose me'.",
  "The realm rewards gentle persistence.",
  "Your light gathers itself.",
  "Treasure found: a moment of peace.",
  "Soft win. Mighty meaning.",
  "You moved the needle inside.",
  "Restored. Renewed. Ready.",
  "The forest of self bows gently.",
  "You did the thing. The kind thing.",
  "Tiny step, vast horizon.",
  "Your story thickens with courage.",
  "Spell complete. HP recovered.",
];

export const RECOVERY_QUOTES = [
  "Healing is progress, even when it feels slow.",
  "Your energy is recovering. Take things one step at a time.",
  "Lay down the heavy quests. Pick up the kind ones.",
  "You are mending. That counts.",
  "Soft days build strong weeks.",
  "Be the safest place in your own day.",
  "Recovery is its own kind of bravery.",
  "Sip water. Breathe. Rest.",
  "You don't have to fix everything today.",
  "The tide is turning, gently.",
  "Your spirit is not broken — it is resting.",
  "Move slow. Heal deep.",
  "Wrap your day in patience.",
  "Light returns in small flickers.",
  "Choose ease today. It is enough.",
  "Even quiet days carry growth.",
  "Restore mode: protect your peace.",
  "Let the world come to you for a while.",
  "You are allowed to need less today.",
  "Tend your inner fire with gentle hands.",
  "Recovery is sacred work.",
  "One soft step at a time, hero.",
  "You don't owe anyone your full battery.",
  "Slowness, too, is forward.",
  "Be the friend you need right now.",
  "Your body and mind are catching up. Wait kindly.",
  "Soft armor is still armor.",
  "Today, choose the gentlest quest.",
  "Whisper kindness to yourself often.",
  "The path is still there when you're ready.",
];

export const EMERGENCY_QUOTES = [
  "You do not need to conquer today. Simply continue.",
  "Your spirit needs rest. Focus on small victories today.",
  "You're safe here. Let's slow down together.",
  "Breath by breath, you return to yourself.",
  "You don't have to fix anything right now. Just be here.",
  "This moment will pass. You'll still be here when it does.",
  "Soft is the bravest thing you can be right now.",
  "Lay it down. Whatever it is. Lay it down.",
  "You are not alone in the dark. Many lanterns are lit.",
  "Hold on softly. That counts as holding on.",
  "Just this breath. Just this one.",
  "There is no quest more important than your safety.",
  "Reach out. A voice is a lifeline.",
  "You're allowed to need help. Asking is brave.",
  "Small. Slow. Safe.",
  "Your feelings are real. So is your strength.",
  "Even the dimmest star is still a star.",
  "You are loved. Even now. Especially now.",
  "Rest your mind on the rhythm of your breath.",
  "Storms pass. You remain.",
  "You don't have to understand it. You just have to survive it.",
  "Wrap yourself in something soft and breathe.",
  "Drink water. Touch something cold. You are here.",
  "You're doing the hardest, quietest kind of brave.",
  "One safe moment at a time.",
  "Let someone hold space for you today.",
  "You matter. Full stop.",
  "The world is brighter with you in it.",
  "Tomorrow is not a promise — it is an invitation.",
  "Stay. Just stay. We'll figure the rest out together.",
];

function dayIndex(): number {
  const d = new Date();
  return Math.floor(d.getTime() / (1000 * 60 * 60 * 24));
}

export function dailyQuote() { return DAILY_QUOTES[dayIndex() % DAILY_QUOTES.length]; }
export function questCompleteQuote() {
  return QUEST_COMPLETE_QUOTES[Math.floor(Math.random() * QUEST_COMPLETE_QUOTES.length)];
}
export function recoveryQuote() {
  return RECOVERY_QUOTES[Math.floor(Math.random() * RECOVERY_QUOTES.length)];
}
export function emergencyQuote() {
  return EMERGENCY_QUOTES[Math.floor(Math.random() * EMERGENCY_QUOTES.length)];
}